name: house-ml
channels:
- defaults
dependencies:
- python
- pip
- beautifulsoup4
- pandas
- psycopg2
- sshtunnel
- streamlit
- sqlalchemy
- geopy
pip:
  - psycopg2-binary


# dev
- black
- flake8
- isort
- jupyter
